FROM python:3.8

WORKDIR /build

ENV PYTHONPATH "${PYTHONPATH}:/build"
ENV PYTHONUNBUFFERED=1

COPY requirements.txt ./
COPY . ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 40002

CMD ["python app.py"]
